Fail and die on failure to file lock, instead of blocking (potential cascade)

diff --git a/run-archive-job b/run-archive-job
--- a/run-archive-job
+++ b/run-archive-job
@@ -30,7 +30,7 @@ done
 
 echo "Acquiring file lock on $LOCK_FILE"
 exec 42>> "$LOCK_FILE"
-flock -x 42
+flock -nx 42 || die "Failed to get file lock - already running?"
 echo "Lock acquired"
 
 if [ -e "$SNAPSHOT_TEMP_FILE" ]; then
